---
title: "Figure6B"
author: "Nan Zhang", "Jing-Min Yang"
output: html_document
date: "2024-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(tibble))
suppressMessages(library(data.table))
suppressMessages(library(magrittr))
suppressMessages(library(survival))
suppressMessages(library(survminer))
suppressMessages(library(paletteer))
suppressMessages(library(ggsignif))
suppressMessages(library(gghalves))
suppressMessages(library(ggradar))
suppressMessages(library(ggh4x))
suppressMessages(library(rstatix))
suppressMessages(library(jjPlot))
source("mytheme.R")

df <- read.csv("Figure6B.csv")
proj <- c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "DLBC", "ESCA", "GBM", "HNSC", "KICH", "KIRC", "KIRP", "LAML", "LGG", "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ", "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS", "UVM")

g_es <- df %>%
  dplyr::select(-c(2:3)) %>%
  column_to_rownames("sample") %>%
  t() %>%
  as.data.frame()
terms <- rownames(g_es)

FUN <- function(cancer) {
  Data5 <- df %>% dplyr::filter(tissue == cancer)
  Data5 <- Data5 %>% dplyr::select(sample, Cytotoxicity)

  res_df <- g_es[, Data5$sample]
  FUN_cor <- function(term) {
    temp_df <- res_df[term, ] %>%
      t() %>%
      as.data.frame() %>%
      rownames_to_column("sample")
    temp_df <- temp_df %>%
      inner_join(Data5, by = "sample") %>%
      column_to_rownames("sample")
    dd <- cor.test(as.numeric(temp_df[, 1]), as.numeric(temp_df[, 2]), method = "spearman")
    temp_df <- data.frame(cancer = cancer, term = term, cor = dd$estimate, pvalue = dd$p.value)
    rownames(temp_df) <- NULL
    return(temp_df)
  }
  temp_l <- lapply(terms, FUN_cor)
  temp_df <- do.call(rbind, temp_l)
  res <- temp_df
  return(res)
}

l <- pbapply::pblapply(proj, FUN = FUN)
data <- do.call(rbind, l)

data$pstar <- ifelse(data$pvalue < 0.05, "*",
  ""
)


p <- ggplot(data, aes(y = term, x = cancer)) +
  geom_tile(aes(fill = cor), colour = "black", size = 0.5) +
  scale_fill_gradientn(colours = RColorBrewer::brewer.pal(11, "Spectral") %>% rev(), limits = c(-0.25, 1)) +
  geom_text(aes(label = pstar), col = "black", size = 7, vjust = 0.7) +
  scale_y_discrete(limits = terms %>% rev(), labels = terms %>% rev() %>% str_replace_all("\\.", " ")) +
  scale_x_discrete(limits = proj %>% str_sort()) +
  theme_blue +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(colour = "black", angle = 90, hjust = 1, size = 12),
    axis.text.y = element_text(colour = "black", angle = 30, hjust = 1, size = 12)
  ) +
  guides(fill = guide_colorbar(
    ticks.colour = "black",
    frame.colour = "black",
    ticks.linewidth = 2,
    frame.linewidth = 2, barwidth = 0.5
  )) +
  labs(fill = paste0(" * p < 0.05", "\n\n", "** p < 0.01", "\n\n", "Coefficients"))
```
