---
title: "Figure4A.rmd"
author: "Nan Zhang","Jing-Min Yang"
output: html_document
date: "2024-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(tibble))
suppressMessages(library(data.table))
suppressMessages(library(magrittr))
suppressMessages(library(survival))
suppressMessages(library(survminer))
suppressMessages(library(paletteer))
suppressMessages(library(ggsignif))
suppressMessages(library(gghalves))
suppressMessages(library(ggradar))
suppressMessages(library(ggh4x))
suppressMessages(library(rstatix))
suppressMessages(library(jjPlot))
source("mytheme.R")

mycol <- c("#223D6C", "#D20A13", "#FFD121", "#088247", "#58CDD9", "#7A142C", "#5D90BA", "#431A3D", "#91612D", "#6E568C", "#E0367A", "#efa666", "#7c6a0a")
names(mycol) <- c("Th", "Tex", "eTreg", "Tn", "nTreg", "Tcm", "Tem", "Temra", "Tscm", "Tc", "Tprolif", "non-Tprolif", "Tfh")

data2 <- read.csv("Figure4A.csv")

data3 <- data2[which(data2$cell_type %in% c("nTreg", "eTreg", "Tn", "Tcm", "Tem", "Tc", "Temra")), ]
data3$cell_type <- factor(data3$cell_type, levels = c("nTreg", "eTreg", "Tn", "Tcm", "Tem", "Tc", "Temra"))
compaired <- list(c("nTreg", "eTreg"), c("Tn", "Temra"))
p1 <- ggplot(data3, aes(cell_type, y = Quiescence, fill = cell_type)) +
  geom_jitter(
    width = 0.2,
    height = 0,
    size = 3,
    shape = 21,
    show.legend = FALSE, stroke = 0.8
  ) +
  scale_fill_manual(values = mycol[c("nTreg", "eTreg", "Tn", "Tcm", "Tem", "Tc", "Temra")]) +
  theme_blue +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black", size = 12), legend.position = "none") + 
  labs(title = "Quiescence", x = NULL, y = NULL) +
  geom_signif(comparisons = compaired, textsize = 8, vjust = 0.6, color = "black", map_signif_level = T, test = wilcox.test) +
  scale_y_continuous(expand = expand_scale(add = c(0.05, 0.05)))

data3 <- data2[which(data2$cell_type %in% c("Th", "Tfh", "Tc")), ]
data3$cell_type <- factor(data3$cell_type, levels = c("Th", "Tfh", "Tc"))
compaired <- list(c("Tfh", "Tc"))
p2 <- ggplot(data3, aes(cell_type, y = Helper, fill = cell_type)) +
  geom_jitter(
    width = 0.2,
    height = 0,
    size = 3,
    shape = 21,
    show.legend = FALSE, stroke = 0.8
  ) +
  scale_fill_manual(values = mycol[c("Th", "Tfh", "Tc")]) +
  theme_blue +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black", size = 12), legend.position = "none") + 
  labs(title = "Helper", x = NULL, y = NULL) +
  geom_signif(comparisons = compaired, textsize = 8, vjust = 0.6, color = "black", map_signif_level = T, test = wilcox.test) +
  scale_y_continuous(expand = expand_scale(add = c(0.05, 0.05)))

data3 <- data2[which(data2$cell_type %in% c("Tprolif", "non-Tprolif")), ]
data3$cell_type <- factor(data3$cell_type, levels = c("Tprolif", "non-Tprolif"))
compaired <- list(c("Tprolif", "non-Tprolif"))
p3 <- ggplot(data3, aes(cell_type, y = Proliferation, fill = cell_type)) +
  geom_jitter(
    width = 0.2,
    height = 0,
    size = 3,
    shape = 21,
    show.legend = FALSE, stroke = 0.8
  ) +
  scale_fill_manual(values = mycol[c("Tprolif", "non-Tprolif")]) +
  theme_blue +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black", size = 12), legend.position = "none") + 
  labs(title = "Proliferation", x = NULL, y = NULL) +
  geom_signif(comparisons = compaired, textsize = 8, vjust = 0.6, color = "black", map_signif_level = T, test = wilcox.test) +
  scale_y_continuous(expand = expand_scale(add = c(0.05, 0.05)))

data3 <- data2[which(data2$cell_type %in% c("Tn", "nTreg", "eTreg")), ]
data3$cell_type <- factor(data3$cell_type, levels = c("Tn", "nTreg", "eTreg"))
compaired <- list(c("nTreg", "eTreg"))
p4 <- ggplot(data3, aes(cell_type, y = Regulating, fill = cell_type)) +
  geom_jitter(
    width = 0.2,
    height = 0,
    size = 3,
    shape = 21,
    show.legend = FALSE, stroke = 0.8
  ) +
  scale_fill_manual(values = mycol[c("Tn", "nTreg", "eTreg")]) +
  theme_blue +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black", size = 12), legend.position = "none") + 
  labs(title = "Regulating", x = NULL, y = NULL) +
  geom_signif(comparisons = compaired, textsize = 8, vjust = 0.6, color = "black", map_signif_level = T, test = wilcox.test) +
  scale_y_continuous(expand = expand_scale(add = c(0.05, 0.05)))

data3 <- data2[which(data2$cell_type %in% c("Tc", "Th")), ]
data3$cell_type <- factor(data3$cell_type, levels = c("Tc", "Th"))
compaired <- list(c("Tc", "Th"))
p5 <- ggplot(data3, aes(cell_type, y = Cytotoxicity, fill = cell_type)) +
  geom_jitter(
    width = 0.2,
    height = 0,
    size = 3,
    shape = 21,
    show.legend = FALSE, stroke = 0.8
  ) +
  scale_fill_manual(values = mycol[c("Tc", "Th")]) +
  theme_blue +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black", size = 12), legend.position = "none") + 
  labs(title = "Cytotoxicity", x = NULL, y = NULL) +
  geom_signif(comparisons = compaired, textsize = 8, vjust = 0.6, color = "black", map_signif_level = T, test = wilcox.test) +
  scale_y_continuous(expand = expand_scale(add = c(0.05, 0.05)))

data3 <- data2[which(data2$cell_type %in% c("Tn", "Tscm", "Tcm", "Tem", "Temra")), ]
data3$cell_type <- factor(data3$cell_type, levels = c("Tn", "Tscm", "Tcm", "Tem", "Temra"))
compaired <- list(c("Tn", "Temra"))
p6 <- ggplot(data3, aes(cell_type, y = Senescence, fill = cell_type)) +
  geom_jitter(
    width = 0.2,
    height = 0,
    size = 3,
    shape = 21,
    show.legend = FALSE, stroke = 0.8
  ) +
  scale_fill_manual(values = mycol[c("Tn", "Tscm", "Tcm", "Tem", "Temra")]) +
  theme_blue +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black", size = 12), legend.position = "none") + 
  labs(title = "Senescence", x = NULL, y = NULL) +
  geom_signif(comparisons = compaired, textsize = 8, vjust = 0.6, color = "black", map_signif_level = T, test = wilcox.test) +
  scale_y_continuous(expand = expand_scale(add = c(0.05, 0.05)))

data3 <- data2[which(data2$cell_type %in% c("Tn", "Tscm", "Tcm", "Tem", "Tc", "Tex")), ]
data3$cell_type <- factor(data3$cell_type, levels = c("Tn", "Tscm", "Tcm", "Tem", "Tc", "Tex"))
compaired <- list(c("Tn", "Tem"))
p7 <- ggplot(data3, aes(cell_type, y = Progenitor_exhaustion, fill = cell_type)) +
  geom_jitter(
    width = 0.2,
    height = 0,
    size = 3,
    shape = 21,
    show.legend = FALSE, stroke = 0.8
  ) +
  scale_fill_manual(values = mycol[c("Tn", "Tscm", "Tcm", "Tem", "Tc", "Tex")]) +
  theme_blue +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black", size = 12), legend.position = "none") + 
  labs(title = "Progenitor exhaustion", x = NULL, y = NULL) +
  geom_signif(comparisons = compaired, textsize = 8, vjust = 0.6, color = "black", map_signif_level = T, test = wilcox.test) +
  scale_y_continuous(expand = expand_scale(add = c(0.05, 0.05)))

data3 <- data2[which(data2$cell_type %in% c("Tn", "Tscm", "Tcm", "Tem", "Tc", "Tex")), ]
data3$cell_type <- factor(data3$cell_type, levels = c("Tn", "Tscm", "Tcm", "Tem", "Tc", "Tex"))
compaired <- list(c("Tem", "Tex"))
p8 <- ggplot(data3, aes(cell_type, y = Terminal_exhaustion, fill = cell_type)) +
  geom_jitter(
    width = 0.2,
    height = 0,
    size = 3,
    shape = 21,
    show.legend = FALSE, stroke = 0.8
  ) +
  scale_fill_manual(values = mycol[c("Tn", "Tscm", "Tcm", "Tem", "Tc", "Tex")]) +
  theme_blue +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = "black", size = 12), legend.position = "none") + 
  labs(title = "Terminal exhaustion", x = NULL, y = NULL) +
  geom_signif(comparisons = compaired, textsize = 8, vjust = 0.6, color = "black", map_signif_level = T, test = wilcox.test) +
  scale_y_continuous(expand = expand_scale(add = c(0.05, 0.05)))

p <- cowplot::plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, align = "hv", nrow = 2)
```
