---
title: "Figure2A.rmd"
author: "Nan Zhang","Jing-Min Yang"
output: html_document
date: "2024-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(tibble))
suppressMessages(library(data.table))
suppressMessages(library(magrittr))
suppressMessages(library(survival))
suppressMessages(library(survminer))
suppressMessages(library(paletteer))
suppressMessages(library(ggsignif))
suppressMessages(library(gghalves))
suppressMessages(library(ggradar))
suppressMessages(library(ggh4x))
suppressMessages(library(rstatix))
suppressMessages(library(jjPlot))
source("mytheme.R")

dat <- read.csv("Figure2A.csv")
min_break <- 0
max_break <- 1
mid_break <- mean(c(min_break, max_break))

p <- ggplot(dat) +
  geom_hline(
    dat = data.frame(y = c(min_break, mid_break, max_break)),
    aes(yintercept = y), color = "lightgrey"
  ) +
  geom_col(aes(x = x, y = y, fill = y),
    position = "dodge2", show.legend = TRUE, alpha = 1, width = 0.6, colour = "black", lwd = 0.8
  ) +
  geom_segment(aes(x = x, y = min_break, xend = reorder(x, y), yend = max_break),
    linetype = "dashed", color = "gray12"
  ) +
  facet_grid(. ~ proj) +
  scale_y_continuous(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), labels = c("0.0", "0.2", "0.4", "0.6", "0.8", "1.0")) +
  coord_polar() +
  labs(x = NULL, y = NULL) +
  theme_blue +
  scale_fill_gradientn("TCSS", colours = c("#0d3b66", "#faf0ca", "#f4d35e", "#ee964b", "#f95738")) +
  guides(fill = guide_colorsteps(barwidth = 15, barheight = .5, title.position = "top", title.hjust = .5, show.limits = F)) +
  theme(legend.position = "bottom")
```
